sudo: required

language: scala

scala:
- 2.11.8

jdk:
- oraclejdk8

script: sbt ++$TRAVIS_SCALA_VERSION compile test docker:stage

cache:
  directories:
    - '$HOME/.ivy2/cache'

services:
  - docker

after_success:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region us-west-2) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - cd target/docker/stage
  - docker build -t test-project .
  - docker images
  - docker tag test-project:latest 248196168117.dkr.ecr.us-west-2.amazonaws.com/test-project:latest
  - docker push 248196168117.dkr.ecr.us-west-2.amazonaws.com/test-project:latest
