steps:

    - label: 'Create AWS ECR repo'
      agents:
        queue: default
      command: |
          make ecr-createrepo
          make ecr-login | buildkite-agent meta-data set "DOCKER_REPO"

    - wait

    - label: ':hammer: Build & Publish'
      agents:
        queue: default
      command: |
          make docker-build
          # push latest
          DOCKER_TAG=latest \
          eval $(buildkite-agent meta-data get "DOCKER_REPO") && \
          make docker-push
          # push bk no
          DOCKER_TAG=${BUILDKITE_BUILD_NUMBER} \
          eval $(buildkite-agent meta-data get "DOCKER_REPO") && \
          make docker-push
          # push git hash
          DOCKER_TAG=${BUILDKITE_COMMIT} \
          eval $(buildkite-agent meta-data get "DOCKER_REPO") && \
          make docker-push

env:
    SERVICE_NAME: smctest
