steps:

    - label: ':docker: :hammer:'
      command: |
          make docker-build
          make ecr-login
          DOCKER_TAG=latest \
          make docker-push
          # push bk no
          DOCKER_TAG=${BUILDKITE_BUILD_NUMBER} \
          make docker-push
          # push git hash
          DOCKER_TAG=${BUILDKITE_COMMIT} \
          make docker-push
      agents:
          queue: default

    - wait

    - label: ':package:'
      command: |
          DOCKER_IMAGE=$(make ecr-uri):${BUILDKITE_BUILD_NUMBER} \
          make ecs-createtask
          make ecs-getrevision | buildkite-agent meta-data set "ecstaskrev"
          make ecs-getcount | buildkite-agent meta-data set "ecsservicecount"
      env:
          TARGET_ENV: qa
      agents:
          queue: default

    - wait

    - label: ':ecs::rocket:'
      command: |
          SVCNT=$(buildkite-agent meta-data get "ecsservicecount") \
          TASKREV=$(buildkite-agent meta-data get "ecstaskrev") \
          make ecs-updateservice
      env:
          TARGET_ENV: qa
      agents:
          queue: default

env:
    SERVICE_NAME: smctest
