steps:

    - label: ':docker: :hammer:'
      agents:
          queue: default
      command: |
          make docker-build
          make ecr-login
          DOCKER_TAG=latest \
          make docker-push
          # push bk no
          DOCKER_TAG=${BUILDKITE_BUILD_NUMBER} \
          make docker-push
          # push git hash
          DOCKER_TAG=${BUILDKITE_COMMIT} \
          make docker-push

    - wait

    - label: ':rocket:'
      agents:
          queue: default
      command: |
          DOCKER_IMAGE=$(make ecr-uri):${BUILDKITE_BUILD_NUMBER} \
          make ecs-createtask
          make ecs-getrevision | buildkite-agent meta-data set "ecstaskrev"

    - wait

    - label: ':ecs:'
      agents:
          queue: default
      command: |
          TASKREV=$(buildkite-agent meta-data get "ecstaskrev") \
          make ecs-updateservice
      env:
          TARGET_ENV: qa
env:
    SERVICE_NAME: smctest
