steps:

    - label: 'Create AWS ECR repo'
      agents:
        queue: default
      command: |
          make create-ecr-repo
          make get-ecr-login | buildkite-agent meta-data set "DOCKER_REPO"

    - wait

    - label: ':hammer: Build & Publish'
      agents:
        queue: default
      command: |
          make docker-build
          # push latest
          export DOCKER_TAG=latest
          eval $(buildkite-agent meta-data get "DOCKER_REPO") && \
          make docker-push
          # push bk no
          export DOCKER_TAG=${BUILDKITE_BUILD_NUMBER}
          eval $(buildkite-agent meta-data get "DOCKER_REPO") && \
          make docker-push
          # push git hash
          export DOCKER_TAG=${BUILDKITE_COMMIT}
          eval $(buildkite-agent meta-data get "DOCKER_REPO") && \
          make docker-push

env:
    SERVICE_NAME: smctest
