steps:

    - label: ':ecs:'
      agents:
          queue: default
      command: |
          make ecr-createrepo

    - wait

    - label: ':docker: :hammer:'
      agents:
          queue: default
      command: |
          make docker-build
          make ecr-login
          DOCKER_TAG=latest \
          make docker-push
          # push bk no
          DOCKER_TAG=${BUILDKITE_BUILD_NUMBER} \
          make docker-push
          # push git hash
          DOCKER_TAG=${BUILDKITE_COMMIT} \
          make docker-push

    - wait

    - label: ':rocket:'
      agents:
          queue: default
      command: |
          sed "s/<DOCKER_IMAGE>/$(make ecr-uri):${BUILDKITE_BUILD_NUMBER}/g" task.json.tmpl > task.json
          make ecs-createtask
env:
    SERVICE_NAME: smctest
