steps:

    - label: 'Create AWS ECR repo'
      agents:
          queue: default
      command: |
          make ecr-createrepo

    - wait

    - label: ':hammer: Build & Publish'
      agents:
          queue: default
      command: |
          make docker-build
          eval $(make ecr-login)
          DOCKER_TAG=latest \
          make docker-push
          # push bk no
          DOCKER_TAG=${BUILDKITE_BUILD_NUMBER} \
          make docker-push
          # push git hash
          DOCKER_TAG=${BUILDKITE_COMMIT} \
          make docker-push

    - wait


    - label: ':deploy:'
      agents:
          queue: default
      command: echo "hello"
env:
    SERVICE_NAME: smctest
