steps:

    - label: ':docker: :hammer:'
      command: |
          make docker-build
          make ecr-login
          DOCKER_TAG=latest \
          make docker-push
          # push bk no
          DOCKER_TAG=${BUILDKITE_BUILD_NUMBER} \
          make docker-push
          # push git hash
          DOCKER_TAG=${BUILDKITE_COMMIT} \
          make docker-push
      agents:
          queue: gapqa
          
    - wait

    - label: ':ecs: QA :rocket:'
      command: |
          CLUSTER_STACK_NAME=qa-ecs \
          TARGET_ENV=qa \
          CNAME=qa-smctest2.gapgov.uk \
          SERVICE_NAME=smctest2 \
          CPU=100 \
          MEMORY=256 \
          DOCKER_IMAGE=smctest2:latest \
          AWS_ENV=qa \
          make create
      env:
          TARGET_ENV: qa
      agents:
          queue: gapqa
 
env:
    SERVICE_NAME: smctest2
