steps:

    - label: 'Create AWS ECR repo'
      agents:
        queue: default
      command: |
          make create-ecr
          DOCKER_REPO=$(aws ecr describe-repositories \
            --repository-names ${BUILDKITE_PIPELINE_SLUG} \
            --query 'repositories[0].repositoryUri')
          buildkite-agent meta-data set DOCKER_REPO ${DOCKER_REPO}
	      DOCKER_LOGIN=$(aws --region ${AWS_REGION} ecr get-login)
          buildkite-agent meta-data set DOCKER_LOGIN ${DOKCER_LOGIN}

    - wait

    - label: ':hammer: Build & Publish'
      agents:
        queue: default
      command: |
          make docker-build
          export DOCKER_REPO=$(buildkite-agent meta-data get "DOCKER_REPO")
          eval $(buildkite-agent meta-data get "DOCKER_LOGIN")
          # push latest
          export DOCKER_TAG=latest
          make docker-push
          # push bk no
          export DOCKER_TAG=${BUILDKITE_BUILD_NUMBER}
          make docker-push
          # push git hash
          export DOCKER_TAG=${BUILDKITE_COMMIT}
          make docker-push


