steps:

    - label: 'Create AWS ECR repo'
      agents:
        queue: default
      command: >
          make create-ecr
          # get erc repo uri
          DOCKER_REPO=$(aws ecr describe-repositories \
            --repository-names ${BUILDKITE_PIPELINE_SLUG} \
            --query 'repositories[0].repositoryUri')
          buildkite-agent meta-data set DOCKER_REPO ${DOCKER_REPO}

    - wait

    - label: ':hammer: Build & Publish'
      agents:
        queue: default
      command: >
          # docker login
          eval $(aws --region eu-west-2 ecr get-login)
          make docker-build
          DOCKER_REPO=$(buildkite-agent meta-data get "DOCKER_REPO")
          DOCKER_TAG=latest make docker-push
          DOCKER_TAG=${BUILDKITE_BUILD_NUMBER} make docker-push
          DOCKER_TAG=${BUILDKITE_COMMIT} make docker-push


